# Write a program to input eight numbers from the user and display all the unique 
# numbers (once).
num=set()
num1=input("enter the number=")
num.add(num1)
num2=input("enter the number=")
num.add(num2)
num3=input("enter the number=")
num.add(num3)
num4=input("enter the number=")
num.add(num4)
num5=input("enter the number=")
num.add(num5)
num6=input("enter the number=")
num.add(num6)
num7=input("enter the number=")
num.add(num7)
num8=input("enter the number=")
num.add(num8)
print(num)